version = 0.1
[default.deploy.parameters]
stack_name = "uni-prop-local-contracts"
resolve_s3 = true
s3_prefix = "uni-prop-local-contracts"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
parameter_overrides = "Stage=\"local\""
image_repositories = []
